### ISSUE TITLE
Steps info text is squished

### ISSUE THREAD

**Issue by martinkf** [raveitoutofficial/raveitout#23]
Steps info text gets very squished as soon as it gets a little big. 

Could use a little more room, maybe as much as the "Speed" text gets; or, better yet, expands even further to the sides towards the unused blank space by the side of the screen.

Being able to display about 40 characters without being squished would be ideal to properly convey full information about PIU mission/quest charts for example, but I understand if it's not feasible to display that many characters over there.

Alternatively, maybe a line break could be possible (?)
![inkedinkedscreenshot 21 _li](https://user-images.githubusercontent.com/6123137/53069710-b7482c80-34bb-11e9-89d0-91af126bfa6f.jpg)

**Comment by RhythmLunatic** [comment]
Fixed.
