### ISSUE TITLE
Group select miscalculating how many songs there are

### ISSUE THREAD

**Issue by martinkf** [raveitoutofficial/raveitout#25]
![inkedinkedscreenshot 25 _li](https://user-images.githubusercontent.com/6123137/53070062-b6fc6100-34bc-11e9-8d12-15ddafc1f3f4.jpg)

**Comment by RhythmLunatic** [comment]
This is a limitation of the current wheel because the info folder takes up a song and it's expected to be there. It will be fixed with a custom wheel.
