### ISSUE TITLE
Add overrides for heart subtraction

### ISSUE THREAD

**Issue by 9xeqt8YziSbF4c** [raveitoutofficial/raveitout#30]
Apparently #SONGTYPE is the standard for PIU simfiles.

**Comment by martinkf** [comment]
Pasting what I mentioned over at Facebook to help
"From what I can observe, they use
#SONGTYPE:ARCADE for regular (2 Hearts)
#SONGTYPE:SHORTCUT for short (1 Heart)
#SONGTYPE:REMIX for long (3 Hearts) and 
#SONGTYPE:FULLSONG for extra-long (4 Hearts)

Those terms of course are based on the Andamiro PIU stuff so a new standard can be set by the RIO developers if you want. Just put it in the Song Structure Documentation txt and then the .ssc's can follow suit :)"

**Comment by RhythmLunatic** [comment]
Added... Sort of.
Hiding overridden songs from the music wheel requires a custom wheel, but for now they will subtract the correct amount of hearts.
