### ISSUE TITLE
AV Option List cursor return to "Exit" button after each press

### ISSUE THREAD

**Issue by martinkf** [raveitoutofficial/raveitout#37]
Ideally, in order to properly input the desired AV value, a player might need several presses of the "AV +100", "AV -10", "AV +10", "AV -100" option buttons. If the cursor returns to "Exit" after each press, it's quite boring having to select the option button you want to input again.

I suppose ideally the cursor should not default to "Exit" after each press, at least in this sub-menu only (?)

**Comment by RhythmLunatic** [comment]
Another "feature" of the OptionsList that cannot be fixed without #39
