### ISSUE TITLE
Option List sub-menu toggling

### ISSUE THREAD

**Issue by martinkf** [raveitoutofficial/raveitout#38]
While in the Option List menu, holding Left and pressing Right (or DownLeft+DownRight) seems to go to the next Option List sub-menu, ignoring completely the flow of the main Option List menu; in the same fashion, holding Right and pressing Left (or DownRight+DownLeft) returns to the previous one.

Not sure if this is something you want to keep, as this button combination can easily be pressed by accident (which has happened to me A LOT, especially since DownLeft and DownRight are directly related to the shortcut that actually launches the Option List)

**Comment by RhythmLunatic** [comment]
It is a "feature" of the stock OptionsList and can't be removed.
