### ISSUE TITLE
The BGAS Of Rave It Out last version didn't work in the stepprime and StepXX, only works in StepF2

### ISSUE THREAD

**Issue by Scampt** [raveitoutofficial/raveitout#49]
Its there any solution to the bgas of RIO works well in the Stepprime or StepXX, i put it in to the SongMovies and didnt load the bg, only apears no background, i got the previews, SD, HD and nothing works, anyone can help me?

**Comment by JapanYoshi** [comment]
Rave It Out is not a normal chart pack, and is not intended to be used for StepPrime, StepXX, or StepF2. Try using [the specialized build](https://github.com/RhythmLunatic/stepmania/tree/starworlds) instead.

Feel free to close the issue if this cleared it up for you.
